logging:
  level:
    org:
      springframework:
        '': INFO
        security: DEBUG
        web: DEBUG
        beans:
          factory: INFO
      quark:
        chores:
          sync: DEBUG

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: ChoresWeb
  datasource:
    url: jdbc:${DB_FLAVOR}://${DB_SERVER}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    Xproperties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
  devtools:
    restart:
      enabled: false

quark:
  sync:
    scaling:
      enabled: false
      max-events: 10000
      stream-key: "choresDataStream"

chores:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  auth:
    issuer: ${ISSUER_URI}
    accessTokenExpiry: ${ACCESS_TOKEN_EXPIRY}
    refreshTokenExpiry: ${REFRESH_TOKEN_EXPIRY}
    clientId: 823804539715-mb7lamcmkpoihnt297fevkrf1h3sgi1f.apps.googleusercontent.com
    secret: ${CHORES_JWT_SECRET:a1d4d689be3962eb4012744d1eb32c834ffcb44f1e451cace4f2c6b18ccda7b3bb03a315b995b3d957b3a99af4f5e95c1571697ea030e1733bb9740e}
  godList: ${DEV_APP_DATA}/godList.txt
  sync:
    cacheTimeout: 20s
